###############
## 
####

GPU: [0]

VERBOSE: True

MODEL:
  MODE: 'Denoising'
  SESSION: 'MPRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 16
  NUM_EPOCHS: 80
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 128
  VAL_PS: 256
  TRAIN_DIR: '/nfs/stak/users/vuonga2/datasets/celeba_prepared/mpr_symlink/train/t100' # path to training data
  VAL_DIR: '/nfs/stak/users/vuonga2/datasets/celeba_prepared/mpr_symlink/test/t100'     # path to validation data
  SAVE_DIR: './checkpoints/celeba_t100'          # path to save models and images
  # SAVE_IMAGES: False
